M48
; DRILL file {KiCad 7.0.10} date Fri Mar  1 22:50:10 2024
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2024-03-01T22:50:10+01:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,7.0.10
; #@! TF.FileFunction,Plated,1,2,PTH
FMAT,2
INCH
; #@! TA.AperFunction,Plated,PTH,ViaDrill
T1C0.0157
; #@! TA.AperFunction,Plated,PTH,ComponentDrill
T2C0.0197
; #@! TA.AperFunction,Plated,PTH,ViaDrill
T3C0.0394
%
G90
G05
T1
X3.52Y-3.045
X3.615Y-3.045
T2
X3.56Y-2.54
X3.56Y-2.5794
X3.56Y-2.6187
X3.56Y-2.6581
T3
X3.67Y-2.56
X3.68Y-2.96
X3.79Y-2.56
M30
